version: "3.1"
services:
  api-database:
    image: mongo:3.2.4
    container_name: "api-database"
    ports:
      - 27017:27017
    command: --smallfiles
  api:
    build: .
    image: api-docker-image
    ports:
      - 9090:8080
    links:
      - api-database
